"""convert bills and transaction to uuid

Revision ID: 988779dc2ef7
Revises: 5115da2a0900
Create Date: 2026-01-27 20:26:56.027105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '988779dc2ef7'
down_revision: Union[str, Sequence[str], None] = '5115da2a0900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - convert bills and transaction to UUID"""
    
    # Convert bills
    op.add_column('bills', sa.Column('id_new', postgresql.UUID(as_uuid=True), nullable=False))
    op.execute('UPDATE bills SET id_new = gen_random_uuid()')
    op.add_column('bills', sa.Column('user_id_new', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute('UPDATE bills SET user_id_new = u.id FROM users u WHERE bills.user_id = u.id')
    op.drop_column('bills', 'user_id')
    op.execute('ALTER TABLE bills RENAME COLUMN user_id_new TO user_id')
    op.alter_column('bills', 'user_id', nullable=False)
    op.drop_column('bills', 'id')
    op.execute('ALTER TABLE bills RENAME COLUMN id_new TO id')
    op.execute('ALTER TABLE bills ADD PRIMARY KEY (id)')
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    
    # Convert transaction
    op.add_column('transaction', sa.Column('id_new', postgresql.UUID(as_uuid=True), nullable=False))
    op.execute('UPDATE transaction SET id_new = gen_random_uuid()')
    op.add_column('transaction', sa.Column('user_id_new', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute('UPDATE transaction SET user_id_new = u.id FROM users u WHERE transaction.user_id = u.id')
    op.drop_column('transaction', 'user_id')
    op.execute('ALTER TABLE transaction RENAME COLUMN user_id_new TO user_id')
    op.alter_column('transaction', 'user_id', nullable=False)
    op.drop_column('transaction', 'id')
    op.execute('ALTER TABLE transaction RENAME COLUMN id_new TO id')
    op.execute('ALTER TABLE transaction ADD PRIMARY KEY (id)')
    
    # Create analysis table with UUID
    op.create_table('analysis',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('bills_count', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Recreate foreign keys
    op.create_foreign_key('bills_user_id_fkey', 'bills', 'users', ['user_id'], ['id'])
    op.create_foreign_key('transaction_user_id_fkey', 'transaction', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema"""
    pass
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('transaction', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.alter_column('bills', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('analysis')
    # ### end Alembic commands ###
